version: '2'
services:

  mailcatcher:
    image: pilothouseapp/mailcatcher:latest
    ports:
      - 1080:1080

  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: root
    image: mariadb:latest
    ports:
      - 3306:3306
    volumes:
      - "{{MYSQL_CONFIG_FILE}}:/etc/mysql/conf.d/pilothouse.cnf"
      - "mysqldata:/var/lib/mysql"

  nginx:
    image: nginx:mainline-alpine
    depends_on:
      - php56
      - php56-xdebug
      - php70
      - php70-xdebug
      - php71
      - php71-xdebug
    ports:
      - 80:80
      - 443:443
    volumes:
      - "{{HTTPS_CERTIFICATE_CERT}}:/etc/nginx/https-certificate.cert"
      - "{{HTTPS_CERTIFICATE_KEY}}:/etc/nginx/https-certificate.key"
      - "{{NGINX_COMPILED_SITES_CONFIG_FILE}}:/etc/nginx/conf.d/default.conf"
      - "{{NGINX_CONFIG_FILE}}:/etc/nginx/nginx.conf"
      - "{{NGINX_DEFAULT_SITE_DIRECTORY}}:/var/www/html/default-site/"
      - "{{SITES_DIRECTORY}}:/var/www/html/sites/"

  php56:
    image: pilothouseapp/php:5.6-dev
    environment:
      - TERM=xterm
    volumes:
      - "{{PHP_CONFIG_FILE}}:/usr/local/etc/php/conf.d/pilothouse.ini"
      - "{{PHP_FPM_CONFIG_FILE}}:/usr/local/etc/php-fpm.d/pilothouse.conf"
      - "{{PHP_XDEBUG_CONFIG_FILE}}:/usr/local/etc/php/conf.d/xdebug.ini"
      - "{{NGINX_DEFAULT_SITE_DIRECTORY}}:/var/www/html/default-site/"
      - "{{SITES_DIRECTORY}}:/var/www/html/sites/"
      - "{{SSMTP_CONFIG_FILE}}:/etc/ssmtp/ssmtp.conf"
      - "/home/www-data/.composer"
      - "/home/www-data/.wp-cli"

  php56-xdebug:
    image: pilothouseapp/php:5.6-xdebug-dev
    extends:
      service: php56

  php70:
    image: pilothouseapp/php:7.0-dev
    extends:
      service: php56

  php70-xdebug:
    image: pilothouseapp/php:7.0-xdebug-dev
    extends:
      service: php56

  php71:
    image: pilothouseapp/php:7.1-dev
    extends:
      service: php56

  php71-xdebug:
    image: pilothouseapp/php:7.1-xdebug-dev
    extends:
      service: php56

  phpmyadmin:
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=root
      - PMA_USER=pilothouse
      - PMA_PASSWORD=pilothouse
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8080:80

  redis:
    image: redis:3-alpine
    ports:
      - 6379:6379

volumes:
  mysqldata:
